### PR TITLE
init commit

### PR DESCRIPTION
**Pull request by TorstenDittmann**
todo:
- [x] add env variables
- [x] typescript stuff
- [x] checking off todos
- [x] adding svelte logo
- [x] cleaning up

### CODE REVIEW

**Comment by christyjacob4** [comment]
Screenshot 2021-04-14 at 12 34 08 AM

@TorstenDittmann  The update todo functionality might need some tweaking. The `line-through` class is doesn't seem to be applying. 

Screenshot 2021-04-14 at 12 35 57 AM
Also, in the login screen , The login button is enabled even If the email and password is empty, 
Similarly in the signup screen.

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
Left some comments

**Comment by TorstenDittmann** [comment]
@christyjacob4 should be fixed now 👍🏻

**Comment by christyjacob4** [comment]
@TorstenDittmann  Looks good 👍

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
